default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pixselsim_development
  username: meriem
  password: Moulou02
  host: localhost
  port: 5433

test:
  <<: *default
  database: pixselsim_test
  username: meriem
  password: Moulou02
  host: localhost
  port: 5433

production:
   primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    migrations_paths: db/queue_migrate